package Szpital;

public enum typ_operacji {
    Chirurgiczne_leczenieo_tyłości,
    Operacja_plastyczna_biustu,
    Chirurgia_okrężnicy_i_odbytnicy,
    Chirurgia_endokrynologiczna,
    Chirurgia_ogólna,
    Chirurgia_ginekologiczna,
    Chirurgia_ręki,
    Chirurgia_głowy_i_szyi,
    Operacja_przepukliny,
    Neurochirurgia,
    Chirurgia_ortopedyczna,
    Chirurgia_okulistyczna,
    Chirurgia_ambulatoryjna,
    Chirurgia_dziecięca,
    Plastic_and_Reconstructive_Surgery,
    Chirurgia_plastyczna_i_rekonstrukcyjna,
    Chirurgia_robotyczna,
    Operacja_klatki_piersiowej,
    Chirurgia_urazowa,
    Chirurgia_urologiczna,
    Chirurgia_naczyniowa,
    Chirurgia_małoinwazyjna,
}
